language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-apps' ]; then cd .. && eval "mv $currentfolder generator-apps" && cd generator-apps; fi
