language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'apps-generator' ]; then cd .. && eval "mv $currentfolder apps-generator" && cd apps-generator; fi
